[versions]
agp = "8.10.1"
junit = "4.13.2"
espressoCore = "3.6.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" } # Added missing dependency
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }